# Generated by Django 5.0.3 on 2024-03-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_entries_user'),
        ('user', '0003_remove_user_secret_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
