# Generated by Django 5.0.3 on 2024-03-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding',
            field=models.BooleanField(default=True),
        ),
    ]
