# Generated by Django 5.0.3 on 2024-03-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_password_hash', models.CharField(max_length=1000)),
                ('password_file', models.CharField(max_length=1000)),
                ('password_dict', models.JSONField(default=dict)),
            ],
        ),
    ]
