# Generated by Django 5.0.3 on 2024-03-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.TextField()),
                ('site_url', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('username', models.TextField(null=True)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Secrets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterkey_hash', models.TextField()),
                ('device_secret', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='PasswordManager',
        ),
    ]
