# Generated by Django 5.0.3 on 2024-03-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_entries_secrets_delete_passwordmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='site_image',
            field=models.TextField(null=True),
        ),
    ]
