# Generated by Django 5.0.3 on 2024-03-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_entries_user_alter_secrets_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secrets',
            name='user',
        ),
    ]
