# Generated by Django 5.0.3 on 2024-03-25 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_remove_secrets_user'),
        ('user', '0003_remove_user_secret_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_related', to='user.userprofile'),
        ),
    ]
